[package]
name = "p2pchat"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1.85"
clap = { version = "4.5.26", features = ["derive", "help"] }
env_logger = "0.11.6"
overwatch-derive = { git = "https://github.com/logos-co/Overwatch.git", version = "0.1.0" }
overwatch-rs = { git = "https://github.com/logos-co/Overwatch.git", version = "0.1.0" }
thiserror = "2.0.11"
tokio = { version = "1.16.1", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[features]
instrumentation = []